= SpringBoot WebApp Demo

https://projects.spring.io/spring-boot[Spring Boot]
looks like a nice way to get started.
This is a trivial webapp created using SpringBoot.

== HowTo

	mvn spring-boot:run

Or, in Eclipse with Spring plugin (or "Spring Tool Suite"), 
right-click project or Application.java, 
then RunAs->Spring Boot Application

Seconds later, connect to 

http://localhost:8000/

Note: that is port 8000, _not_ the usual 8080, to avoid conflicts.
Change this in application.properties if you don't like it.

Fill in the form and click Submit.

== War Packaging for EE App Server Deployment

See the section entitled "Traditional Deployment"--"Create a deployable war file" in
the spring-boot reference manual (Section 85.1 as of
this writing).
I've already added the "extends SpringBootServletInitializer" code
and changed the packaging to "war" - it still works in Maven and Eclipse with these settings -
but you must change the embedded container to "provided" in _pom.xml_ before packaging,
otherwise you will probably get class-loading conflicts.

