= SpringBoot WebApp Demo

https://projects.spring.io/spring-boot[Spring Boot]
looks like a nice way to get started.
This is a trivial webapp created using SpringBoot.

== HowTo

	mvn spring-boot:run

Or, in Eclipse with Spring plugin (or "Spring Tool Suite"), 
right-click project or Application.java, 
then RunAs->Spring Boot Application

Seconds later, connect to 

http://localhost:8000/

Note: that is port 8000, _not_ the usual 8080, to avoid conflicts.
Change this in application.properties if you don't like it.

Fill in the form and click Submit.

== War Deployment

It seems that you can't have both the instant-deployment convenience of
Spring Boot AND the security of a full WAR deployment in the same POM file.
If you try deploying this as a war on Wildfly, for example, you get:

	java.lang.NoSuchMethodError: org.apache.tomcat.util.descriptor.DigesterFactory.newDigester(ZZLorg/apache/tomcat/util/digester/RuleSet;Z)Lorg/apache/tomcat/util/digester/Digester

You may need to make some changes to deploy as a WAR file. See the
section entitled "Traditional Deployment"--"Create a deployable war file" in
the spring-boot reference manual (Section 73.1 in the current snapshot as of
this writing).
